### ISSUE TITLE
Helm Getter does not handle relative urls in index.yaml file

### ISSUE THREAD

**Issue by matteogastaldello** [krateoplatformops/core-provider#48]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by matteogastaldello** [comment]
The problem is verified when index.yaml file contains relative urls


```
apiVersion: v1

entries:

  krateo-springboot-webapp:

  - name: krateo-springboot-webapp

    description: A Helm chart for Kubernetes

    version: 0.1.1

    created: 2024-07-09T07:43:14.713Z

    appVersion: 0.1.0

    urls:

    - krateo-springboot-webapp-0.1.1.tgz

generated: 2024-07-09T08:18:29.019Z
```
